server:
  port: 8083
google:
  find:
    place:
      url: https://maps.googleapis.com/maps/api/place/findplacefromtext/json?
  search:
    nearby:
      url: https://maps.googleapis.com/maps/api/place/nearbysearch/json?
  test:
    api:
      key: AIzaSyCny3GMP4sw7JKKJzQOwYJog5L5jDMHMrs
spring:
  datasource:
    password: select_food
    url: jdbc:postgresql://localhost:9006/select_food
    username: select_food
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true