server:
  port: 8083
google:
  host:
    schema: https
  place:
    url: maps.googleapis.com/maps/api/place
  findfromtext:
    url: /findplacefromtext/json
  searchnearby:
    url: /nearbysearch/json
  api:
    key: 

spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:9006/select_food
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true