server:
  port: 8083
spring:
  datasource:
    password: select_food
    url: jdbc:postgresql://localhost:9006/select_food
    username: select_food
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true