server:
  port: 8080
google:
  host:
    schema: https
  place:
    url: maps.googleapis.com/maps/api/place
  findfromtext:
    url: /findplacefromtext/json
  searchnearby:
    url: /nearbysearch/json
  api:
    key:

spring:
  datasource:
    password: passwordd
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

selectfood:
  app:
    jwtSecret: jwtsecrt
    jwtExpirationMs: 86400000

allowed:
  origin: https://select-food-front.herokuapp.com