version: '3.3'
services:
  db:
    container_name: postgres_select_food_db
    image: postgres:10
    volumes:
      - app-db-data:/data
    ports:
      - "9006:5432"
    environment:
      POSTGRES_DB: "select_food"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: "select_food"
      POSTGRES_PASSWORD: "select_food"
    networks:
      - select_food_network

  pgadmin:
    container_name: pgadmin4_select_food
    image: dpage/pgadmin4:6.4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - select_food_network
    ports:
      - "5051:80"
volumes:
  app-db-data:
networks:
  select_food_network:

